### ISSUE TITLE
`tab_width` and `indent_size` shouldn't be mutual exclusive

### ISSUE THREAD

**Issue by ebraminio** [editorconfig/editorconfig-vscode#190]
[HarfBuzz](https://github.com/harfbuzz/harfbuzz) (a highly used font related Linux package) uses a mix of tabs and spaces, see this for example https://github.com/harfbuzz/harfbuzz/pull/292

- [x] I have a question that is specific to this extension; thus, inappropriate for the main [EditorConfig issue tracker](https://github.com/editorconfig/editorconfig/issues).
- [x] I tried running `code --disable-extensions` and the issue did **NOT** present itself.

## Issue

|             | Visual Studio Code | editorconfig-vscode |
|-------------|--------------------|---------------------|
| **Version** | `1.20.1`            | `0.12.1`             |

### Root `.editorconfig` File
```ini
root = true

[*.{c,cc,h,hh}]
indent_style = space
tab_width = 8
indent_size = 2
```

Are there any other relevant `.editorconfig` files in your project? No

### File opened
Open https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-aat-layout-morx-table.hh with vscode

### Expected behavior
What is expected is somewhere between having or not having of indent_size, for example on this [file](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-aat-layout-morx-table.hh) it should be looked like and will happen if I remove `indent_size = 2` from .editorconfig:
![screen shot 2018-02-20 at 2 30 00 pm](https://user-images.githubusercontent.com/833473/36420513-967f6238-164a-11e8-9b81-a326fe6fa569.png) however the issue is if I comment that line out and try to write something on a function block it will become like:
![screen shot 2018-02-20 at 2 32 26 pm](https://user-images.githubusercontent.com/833473/36420628-eb5c1d78-164a-11e8-892c-b6fca19e6070.png)

### Actual behavior
But without commenting `indent_size = 2` that it will look like:
![screen shot 2018-02-20 at 2 31 33 pm](https://user-images.githubusercontent.com/833473/36420585-c6a03d48-164a-11e8-87ea-ef089132169c.png)

**Comment by jedmao** [comment]
@ebraminio are you sure the issue didn't present itself with `code --disable-extensions`? This looks like a vscode issue to me, as once you enter spaces for indentation or tabs for indentation, it's an exclusive setting.

**Comment by ebraminio** [comment]
> are you sure the issue didn't present itself with `code --disable-extensions`?

You are definitely right on that. In fact even Atom had the same issue so no point on having this file I guess.

**Comment by jedmao** [comment]
If all you're using it for is indentation rules, then yes, I would say no point in using the file in your case.

Out of curiosity, is your indentation setup ideal according to anyone? Or would you prefer it started off with different rules?

**Comment by ebraminio** [comment]
> Out of curiosity, is your indentation setup ideal according to anyone? Or would you prefer it started off with different rules?

It is not appealing to me to be honest but it seems it is some kind of convention on gnome/freedesktop projects. I wanted to improve the situation for myself by https://github.com/harfbuzz/harfbuzz/pull/810 but it seems I am out of luck and I should try Vim and tools the project programmers use mostly.

**Comment by ebraminio** [comment]
> having this file I guess.

By file I meant this issue, that you've closed it, not the .editorconfig, which does some other good things :) (and I am switching between the two modes, `indent_size = 2` for editing, `#indent_size = 2` for viewing, so it has some use to me at least :P)

**Comment by ebraminio** [comment]
Asked on https://github.com/Microsoft/vscode/issues/44438 also

**Comment by dlech** [comment]
The technical limitation in VS Code has been fixed by https://github.com/Microsoft/vscode/pull/62079, which will hopefully be in the 1.32 release.

So, this issue can be re-opened. The editorconfig extension will need to be modified to use the new `editor.indentSize` setting.

**Comment by ebraminio** [comment]
The vscode issue is resolved but what I should use to get the support on the source? Can you open https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-aat-layout-morx-table.hh to see what should I use? I am using this https://github.com/harfbuzz/harfbuzz/blob/master/.editorconfig not sure if is the intended one.

**Comment by dlech** [comment]
The VS Code issue was not resolved after all. The public part of the changes were backed out at the last minute (for good reason). I haven't been able to prioritize continuing the work since then.

**Comment by ebraminio** [comment]
Oh, I didn't know, ok

**Comment by jedmao** [comment]
Closing, because this issue is an issue with the [EditorConfig Specification](https://editorconfig-specification.readthedocs.io/) and not solely with this extension.
